### ISSUE TITLE
Any MacOS examples available?

### ISSUE THREAD

**Issue by armaandh** [kat-tax/ult#1]
Trying to look into how to get started with this. Any examples available for MacOS? Really appreciate your effort.

**Comment by Cavitt** [comment]
I'm finishing up the default project template which will include MacOS.
Should be done in the next couple of days.

**Comment by armaandh** [comment]
Thanks so much, can't wait to start using this!

**Comment by Cavitt** [comment]
Sorry for the delayed response on this. I've tried multiple versions of the Mac RN fork but haven't been able to get it working with the other platforms.

I'm focusing on Web, Android, iOS, and Windows until the [RN for Windows & Mac fork by MS](https://microsoft.github.io/react-native-windows/) supports at least 0.61.5.

**Comment by Cavitt** [comment]
Implemented MacOS support in #4
