### ISSUE TITLE
failed to create project using npx ult

### ISSUE THREAD

**Issue by Raksani** [kat-tax/ult#12]
$ npx ult my-project-ult
npx: installed 43 in 2.748s
Creating project, please wait...
Failed to create project. (1)

**Comment by Cavitt** [comment]
@Raksani thank you for the report.

The issue you're having is the name `my-project-ult` is invalid.
You should use camelcase `MyProjectUlt` or all lowercase, hyphens are invalid.
This does highlight an issue with the error feedback, you shouldn't just get a number, the error should be clear.

tldr: `npx ult MyProjectUlt` should work, error reporting will be improved.

**Comment by Cavitt** [comment]
Released an update to improved the error handling & project name verification in `v0.3.6`.

**Comment by Raksani** [comment]
Thank you, I rename my project to 'myproject' and it works!
However, after I tried to use ' npm run web '. These errors occurred.

> ult-scripts start

env: node\r: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! myproject@0.0.1 web: `ult-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the myproject@0.0.1 web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Do I miss any steps?


Thank you for your help.

**Comment by Cavitt** [comment]
@Raksani this looks like a line-ending issue. I will do some investigating later this evening and get back to you.

**Comment by Cavitt** [comment]
@Raksani I believe I've fixed your issue.
Could you recreate a project or update the following dev dependency:
`"ult-scripts": "^0.3.17"`

**Comment by Cavitt** [comment]
For future reference this was due to a bin JS file having the wrong line endings (CLRF)
MacOS and Linux systems would break. Corrected by adding a gitattributes file and changing the line endings.
