### ISSUE TITLE
'react-native-template-ult-template-default@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by LionelHoudelier** [kat-tax/ult#16]
Hi Cavitt,
For a new project, I get this message for some days: 
'react-native-template-ult-template-default@latest' is not in the npm registry.
It is a new error, isn't it. You are updating?

**Comment by Cavitt** [comment]
Thanks for the report, I'm currently refactoring things. I will investigate this.

**Comment by LionelHoudelier** [comment]
OK. Good job.
Just to give you more info: on `npx ult <appName>`, it crashes with:
>info Setting up new React Native app in /Users/Celine/testult2
>info Fetching template react-native-template-ult-template-default...
>npm ERR! code E404

**Comment by Cavitt** [comment]
@LionelHoudelier this should be fixed.
If you're still having issues could you provide me your node/npm version.

**Comment by LionelHoudelier** [comment]
Thanks for the update. It works perfect on mac but on windows, I (still) get this error (xp dev is difficult I admit ;-)):

> error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-ult-template-default: Not found".
> info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\lpub0\\demo3\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> yarn remove v1.22.5
> [1/2] Removing module react-native-template-ult-template-default...
> error This module isn't specified in a package.json file.
> info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
> warn Failed to clean up template temp files in node_modules/react-native-template-ult-template-default. This is not a critical error, you can work on your app.
