### ISSUE TITLE
Npm run <anything> = Error

### ISSUE THREAD

**Issue by bresnow** [kat-tax/ult#17]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /root/fltngmmth02/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/root/fltngmmth02/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-15T17_04_02_094Z-debug.log

......

Log says package.JSON can't be found

I'm running on a Linux 18 Virtual Machine ...   Node 12.19

**Comment by Cavitt** [comment]
Make sure to run `cd ProjectName` after `npx ult ProjectName` before running `npm ...`.
It's complaining it can't find the package.json, which hints that you're not in the project root directory.

**Comment by bresnow** [comment]
sorry for the delayed reply. i was in the right directory. My watcher limit was too low. i'm all good now
